package Com.march9.TryResources;

public class Test 
{
	 public static void main(String[] args) throws Exception
	 {
	       /* try 
	        {
	            int[] arr = new int[5];
	            arr[10] = 15;
	        } catch (ArrayIndexOutOfBoundsException e) {
	            System.out.println("Exception caught: " + e.getMessage());
	        } finally {
	            System.out.println("Finally block executed.");
	        }*/
		 
		/* try {
	            int[] nums = {1, 2, 3};
	            System.out.println(nums[3]);
	        } catch (ArrayIndexOutOfBoundsException e) {
	            System.err.println("ArrayIndexOutOfBoundsException occurred.");
	        } finally {
	            System.out.println("End of program.");
	        }*/
		 
		 
		/* try {
	            String str = null;
	            System.out.println(str.length());
	        } catch (NullPointerException e) {
	            System.out.println("NullPointerException occurred.");
	        } finally {
	            System.out.println("End of program.");
	        }*/
		 

		 
		 /* try {
	            int num1 = Integer.parseInt(args[0]);
	            int num2 = Integer.parseInt(args[1]);
	            int result = num1 / num2;
	            System.out.println("The result is: " + result);
	        } catch (ArithmeticException e) {
	            System.out.println("Cannot divide by zero.");
	        } catch (ArrayIndexOutOfBoundsException e) {
	            System.out.println("Please provide two integers as command-line arguments.");
	        } catch (NumberFormatException e) {
	            System.out.println("Please provide valid integers as command-line arguments.");
	        } finally {
	            System.out.println("End of program.");
	        } */
		 
		 
		/* try {
	            int num = Integer.parseInt("abc");
	            System.out.println("The number is: " + num);
	        } catch (NumberFormatException e) {
	            System.out.println("NumberFormatException occurred.");
	        } finally {
	            System.out.println("End of program.");
	        }*/
		 
		 
//		    int num = 10;
//	        if (num > 5)
//	        {
//	            new Exception("Invalid number.");
//	        }
//	        System.out.println("End of program.");
//	    

//            try {
//            	new Exception("Invalid number: ");
//            }
//            catch(Exception e)
//            {
//            	System.out.println(e);
//            }
    
		 
		 
		 
		 
		 
		 
		 
		 
		 
		 
		 
	    }


}
